<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <AssemblyName>AldenteaWpfFramework</AssemblyName>
    <RootNamespace>Aldentea.Wpf.Application</RootNamespace>
    <Version>8.0.0</Version>
    <Authors>aldentea</Authors>
    <Copyright>aldentea (c) 2014</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Document\Document.csproj" />
  </ItemGroup>

</Project>