<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>Aldentea.Wpf.Utility</RootNamespace>
    <AssemblyName>AldenteaWpfUtility</AssemblyName>
    <AssemblyVersion></AssemblyVersion>
    <FileVersion></FileVersion>
    <Authors>aldentea</Authors>
    <Version>8.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>